artifacts_root: artifacts
plot_dir: artifacts/plot


# DATA CORRECTION
data_correction:
      # input 
      train_data_path: artifacts/data_ingestion/train_data.pkl

      # output
      root_dir: artifacts/data_correction_${C}

# DATA TRANSFORMATION
data_transformation:
      # input 
      data_correction_path: artifacts/data_correction_${CP}
      weights_path: artifacts/data_transformation_${WEIGHTED}/weights.pkl
      val_data_path: artifacts/data_ingestion/val_data.pkl
      

      # output
      root_dir: artifacts/data_transformation_${P}

# MODEL TRAINING
model_trainer:
      # input
      data_transformation_path: artifacts/data_transformation_${PT}

      # output
      root_dir: artifacts/model_trainer/${T}

# MODEL EVALUATION ON TRAIN VAL
model_evaluation_on_train_val: 
      # input 
      data_transformation_path: artifacts/data_transformation_${PV}
      model_path: artifacts/model_trainer/${MV}/${MIV}.pkl

      # output 
      root_dir: artifacts/model_evaluation_on_train_val/${MV}/${MIV}

# TEST DATA CORRECTION 
test_data_correction: 
      # input 
      test_raw_data_path: artifacts/data_ingestion/test_data.pkl
      preprocessor_path: artifacts/data_correction_${CE}/preprocessor.pkl

      # output
      root_dir: artifacts/test_data_correction


# MODEL_EVALUATION
model_evaluation:
      # input
      test_data_path: artifacts/test_data_correction/test_data.pkl
      data_transformation_path: artifacts/data_transformation_${PE}
      model_path: artifacts/model_trainer/${ME}/{MIE}.pkl

      # output
      root_dir: artifacts/model_evaluation/${ME}/${MIE}
