# COMMON
scoring: accuracy
target_score: 0.99

# DATA CORRECTION
data_correction: 
      name: dc3_new2    # id của data correction 

# DATA TRANSFORMATION
data_transformation: 
      number: dt2_new   # weighted 
      data_correction_name: dc2_new  
      do_smote: f # t: true, f: false
      list_after_feature_transformer: []

      # dành cho weighted
      weights: dt1_new



# MODEL TRAINING  
model_trainer: 
      model_name: model7   # mt: multithreading
      data_transformation_name: dt2_new
      model_train_num: 35
      model_training_type: m  # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal, m: many models

      # Cần cho model_training_type = rcv, gcv, r, g
      base_model: XGBClassifier(random_state=42)
      n_iter: 1 # số tổ hợp chọn khi chạy random search
      param_grid:
            n_estimators: 100-200
            max_depth: 10-20
            reg_alpha: 0-1
            reg_lambda: 1-5
            learning_rate: 10
            subsample: 0.9-1
            colsample_bytree: 0.9-1

      # Càn cho model_training_type = m
      models: 
            - XGBClassifier(n_estimators=300, max_depth=30, reg_alpha=10, reg_lambda=10, learning_rate=0.005)|3



# MODEL EVALUATION ON TRAIN VAL
model_evaluation_on_train_val: 
      data_transformation_number: dt1
      model_name: model1
      model_index: 1
                  
# MODEL EVALUATION
model_evaluation: 
      data_correction_name: dc1
      data_transformation_no: dt1
      model_name: XGB_12

# MONITOR PLOT
monitor_plotter:
      target_val_value: 99
      max_val_value: 100
      dtick_y_value: 5000
